server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /var/lib/promtail/positions/REPLACE_HOST_LABEL.yml

clients:
  - url: http://192.168.1.104:3100/loki/api/v1/push

scrape_configs:
  - job_name: containers
    static_configs:
      - targets:
          - localhost
        labels:
          job: containerlogs
          __path__: /var/lib/docker/containers/*/*-json.log
          host: "REPLACE_HOST_LABEL"

    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            attrs:
      - json:
          source: attrs
          expressions:
            tag:
      - regex:
          source: tag
          expression: '^(?P<container_name>(?:[^_]+_){2}[^_]+)'
      - timestamp:
          source: time
          format: RFC3339Nano
      - labels:
          stream:
          container_name:
      - output:
          source: output

  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: systemlogs
          __path__: /var/log/messages
          host: "REPLACE_HOST_LABEL"

    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\w+\s+\d+\s+\d+:\d+:\d+)\s+(?P<hostname>\S+)\s+(?P<service>\S+?):\s+(?P<message>.*)'
      - timestamp:
          source: timestamp
          format: 'Jan 02 15:04:05'
          location: 'Europe/Istanbul'
      - labels:
          service:
      - output:
          source: message
