global:
  smtp_smarthost: '${SMTP_SMARTHOST}'
  smtp_from: '${SMTP_FROM}'
  smtp_auth_username: '${SMTP_AUTH_USERNAME}'
  smtp_auth_password: '${SMTP_AUTH_PASSWORD}'

route:
  group_by: ['alertname', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: 'default'
  routes:
    - match:
        severity: 'critical'
      receiver: 'critical-alerts'
      repeat_interval: 1h
    - match_re:
        severity: '.*'
      receiver: 'email-notifications'

receivers:
  - name: 'default'
    email_configs:
      - to: '${ALERT_RECIPIENT_EMAIL}'
        send_resolved: true
  - name: 'email-notifications'
    email_configs:
      - to: '${ALERT_RECIPIENT_EMAIL}'
        send_resolved: true
  - name: 'critical-alerts'
    email_configs:
      - to: '${ALERT_RECIPIENT_EMAIL}'
        send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']
