

networks:
  monitoring-net:
    driver: bridge

volumes:
  grafana-data:
    driver: local

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - /datapool/config/prometheus:/etc/prometheus:ro
      - /datapool/config/prometheus/data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=30d'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'
    environment:
      - TZ=${TZ:-Europe/Istanbul}
      - PUID=1000
      - PGID=1000
    user: "1000:1000"
    networks:
      - monitoring-net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - /datapool/config/grafana/data:/var/lib/grafana
      - /datapool/config/grafana/provisioning:/etc/grafana/provisioning:ro
      - /datapool/config/grafana/dashboards:/var/lib/grafana/dashboards:ro
    user: "1000:1000"
    environment:
      - TZ=${TZ:-Europe/Istanbul}
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - PUID=1000
      - PGID=1000
    networks:
      - monitoring-net
    depends_on:
      - prometheus
      - loki
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  loki:
    image: grafana/loki:latest
    container_name: loki
    restart: unless-stopped
    ports:
      - "3100:3100"
    volumes:
      - /datapool/config/loki:/etc/loki:ro
      - /datapool/config/loki/data:/loki/data
    command: -config.file=/etc/loki/loki.yml
    user: "1000:1000"
    environment:
      - TZ=${TZ:-Europe/Istanbul}
      - PUID=1000
      - PGID=1000
    networks:
      - monitoring-net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"


  promtail:
    image: grafana/promtail:latest
    container_name: promtail-monitoring
    restart: unless-stopped
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/log:/var/log:ro
      - /datapool/config/promtail:/etc/promtail:ro
      - /datapool/config/promtail/positions:/var/lib/promtail/positions:rw
    command: -config.file=/etc/promtail/promtail.yml
    environment:
      - TZ=${TZ:-Europe/Istanbul}
      - PUID=1000
      - PGID=1000
    ports:
      - "9080:9080"
    networks:
      - monitoring-net
    depends_on:
      - loki
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  prometheus-pve-exporter:
    image: prompve/prometheus-pve-exporter:latest
    container_name: prometheus-pve-exporter
    restart: unless-stopped
    ports:
      - "9221:9221"
    environment:
      - TZ=${TZ:-Europe/Istanbul}
      - PVE_USER=${PVE_USER}
      - PVE_PASSWORD=${PVE_PASSWORD}
      - PVE_URL=${PVE_URL}
      - PVE_VERIFY_SSL=${PVE_VERIFY_SSL}
      - PUID=1000
      - PGID=1000
    networks:
      - monitoring-net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower-monitoring
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=${TZ:-Europe/Istanbul}
      - WATCHTOWER_CLEANUP=true
      - PUID=1000
      - PGID=1000
      - UMASK=002
    command: ["--schedule", "0 0 2,8,14,20 * * *"]
    networks:
      - monitoring-net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"