global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "/etc/prometheus/rules/*.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Docker Engine daemon metrics (only for Docker-enabled LXCs)
  - job_name: 'docker_engine'
    static_configs:
      - targets:
        - '192.168.1.100:9323'  # proxy
        - '192.168.1.101:9323'  # media
        - '192.168.1.102:9323'  # files
        - '192.168.1.103:9323'  # webtools
        - '192.168.1.104:9323'  # monitoring
        - '192.168.1.105:9323'  # gameservers
        # Note: LXC 150 (backup) and 151 (development) excluded - no Docker
    relabel_configs:
      - source_labels: [__address__]
        regex: '192.168.1.100:9323'
        target_label: instance
        replacement: 'lxc-proxy-01'
      - source_labels: [__address__]
        regex: '192.168.1.101:9323'
        target_label: instance
        replacement: 'lxc-media-01'
      - source_labels: [__address__]
        regex: '192.168.1.102:9323'
        target_label: instance
        replacement: 'lxc-files-01'
      - source_labels: [__address__]
        regex: '192.168.1.103:9323'
        target_label: instance
        replacement: 'lxc-webtools-01'
      - source_labels: [__address__]
        regex: '192.168.1.104:9323'
        target_label: instance
        replacement: 'lxc-monitoring-01'
      - source_labels: [__address__]
        regex: '192.168.1.105:9323'
        target_label: instance
        replacement: 'lxc-gameservers-01'

  

  # Proxmox VE Exporter
  - job_name: 'proxmox'
    static_configs:
      - targets:
        - '192.168.1.10' # Your Proxmox IP
    metrics_path: /pve
    params:
      module: [default]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: prometheus-pve-exporter:9221 # The exporter's address

  # Proxmox Backup Server (via file discovery)
  - job_name: 'pbs'
    metrics_path: /api2/prometheus/metrics
    scheme: https
    tls_config:
      insecure_skip_verify: true
    file_sd_configs:
      - files:
        - /etc/prometheus/pbs_job.yml
        refresh_interval: 1m

  # Loki for log aggregation
  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']

  # Promtail for log shipping
  - job_name: 'promtail'
    static_configs:
      - targets: ['promtail-monitoring:9080']