

networks:
  media-net:
    driver: bridge

services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Istanbul
    volumes:
      - /datapool/config/sonarr:/config
      - /datapool:/datapool
    ports:
      - "8989:8989"
    networks:
      - media-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8989/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Istanbul
    volumes:
      - /datapool/config/radarr:/config
      - /datapool:/datapool
    ports:
      - "7878:7878"
    networks:
      - media-net
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Istanbul
    volumes:
      - /datapool/config/bazarr:/config
      - /datapool:/datapool
    ports:
      - "6767:6767"
    networks:
      - media-net
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Istanbul
    volumes:
      - /datapool/config/jellyfin:/config
      - /datapool:/datapool
    ports:
      - "8096:8096"
    networks:
      - media-net
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    depends_on:
      - jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Istanbul
    volumes:
      - /datapool/config/jellyseerr:/app/config
    dns:
      - 8.8.8.8
    ports:
      - "5055:5055"
    networks:
      - media-net
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Istanbul
      - WEBUI_PORT=8080
    volumes:
      - /datapool/config/qbittorrent:/config
      - /datapool:/datapool
    ports:
      - "8080:8080"
      - "6881:6881"
      - "6881:6881/udp"
    networks:
      - media-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/v2/app/version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Istanbul
    volumes:
      - /datapool/config/prowlarr:/config
    ports:
      - "9696:9696"
    networks:
      - media-net
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=flaresolverr
      - TZ=Europe/Istanbul
      - PUID=1000
      - PGID=1000
      - UMASK=002
    ports:
      - "8191:8191"
    networks:
      - media-net
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  recyclarr:
    image: recyclarr/recyclarr:latest
    container_name: recyclarr
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Istanbul
    volumes:
      - /datapool/config/recyclarr:/config
    networks:
      - media-net
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"


  promtail:
    image: grafana/promtail:latest
    container_name: promtail-media
    restart: unless-stopped
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/log:/var/log:ro
      - /datapool/config/promtail:/etc/promtail:ro
      - /datapool/config/promtail/positions:/var/lib/promtail/positions:rw
    command: -config.file=/etc/promtail/promtail.yml
    environment:
      - TZ=${TZ:-Europe/Istanbul}
      - PUID=1000
      - PGID=1000
    ports:
      - "9080:9080"
    networks:
      - media-net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower-media
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=${TZ:-Europe/Istanbul}
      - WATCHTOWER_CLEANUP=true
      - PUID=1000
      - PGID=1000
      - UMASK=002
    command: ["--schedule", "0 0 2,8,14,20 * * *"]
    networks:
      - media-net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  cleanuperr:
    image: ghcr.io/cleanuparr/cleanuparr:latest
    container_name: cleanuperr
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Istanbul
      - PORT=11011
      - BASE_PATH=
    volumes:
      - /datapool/config/cleanuperr:/config
      - /datapool:/datapool
    ports:
      - "11011:11011"
    networks:
      - media-net
    restart: unless-stopped
    depends_on:
      - sonarr
      - radarr
      - qbittorrent
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"