# Base Game Servers Stack - Watchtower and Shared Network Only
# Use this as the foundation, then deploy individual games separately
---
networks:
  gameserver-net:
    driver: bridge

services:
  promtail:
    image: grafana/promtail:latest
    container_name: promtail-gameservers
    restart: unless-stopped
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/log:/var/log:ro
      - /datapool/config/promtail:/etc/promtail:ro
      - /datapool/config/promtail/positions:/var/lib/promtail/positions:rw
    command: -config.file=/etc/promtail/promtail.yml
    environment:
      - TZ=${TZ:-Europe/Istanbul}
      - PUID=1000
      - PGID=1000
    ports:
      - "9080:9080"
    networks:
      - gameserver-net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower-gameservers
    environment:
      - TZ=${TZ:-Europe/Istanbul}
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=3600  # Check every hour
      - WATCHTOWER_ROLLING_RESTART=true
      - PUID=1000
      - PGID=1000
      - UMASK=002
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - gameserver-net
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
