# Palworld Game Server Only
# Run this AFTER the base stack (docker-compose.yml) is already running
# Uses the existing gameserver-net network created by base stack
---
networks:
  gameserver-net:
    external: true

services:
  palworld-server:
    image: jammsen/docker-palworld-dedicated-server:latest
    container_name: palworld-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Istanbul
      - COMMUNITY_SERVER=false
      - MULTITHREAD_ENABLED=true
      - PUBLIC_IP=
      - PUBLIC_PORT=8211
      - SERVER_NAME=Proxmox Homelab Palworld
      - SERVER_DESCRIPTION=Homelab Palworld Server
      - ADMIN_PASSWORD=homelab123
      - SERVER_PASSWORD=
      - MAX_PLAYERS=32
      - UPDATE_ON_BOOT=true
    volumes:
      - /datapool/config/palworld:/palworld
    ports:
      - "8211:8211/udp"  # Game port
      - "27015:27015/udp"  # Query port
    networks:
      - gameserver-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "netstat -an | grep -q ':8211'"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
